### PR TITLE
Installation and local build need to mention rust

### PR DESCRIPTION
**Pull request by Pike**
Rust needs to have the iOS targets installed.

Grabbed the list from https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-06-rust-on-ios.html

Also `brew install swift-protobuf`

### CODE REVIEW

**Comment by joeyg** [comment]
Is lockwise's swift version not matching the version building the application-services dependency? Previously we have worked to avoid having developers install rust in order to build lockbox.

**Comment by Pike** [comment]
```
*** Downloading application-services.framework binary at "0.27.0.1 Xcode 10.2 build of 0.27"
***  Skipped installing application-services.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)."
```

That might also explain why the XCode build doesn't work afterwards, it doesn't find `MozillaAppServices`. Which are in `Carthage/Build/iOS/Static/MozillaAppServices.framework/` locally, I think. I wonder if the `Static` is throwing it off?

**Comment by joeyg** [comment]
@Pike do you have Xcode 10.2.1? That is the version that ships Swift 5.0.1

**Comment by sashei** [comment]
@Pike yeah, we pin developers to a specific Xcode version rather than enforcing our contributors get their rust env setup

**Comment by Pike** [comment]
So, with some luck, I got to a working local build. There's also been a few github API failures, which can randomly also hit the rust parts. Killing that and trying again helped.

**Comment by sashei** [comment]
@Pike 😳 thanks for updating our version documentation!!

**Comment by devinreams** [comment]
TIL 🌈 

I feel like I got lucky and actually "received" this Xcode update, otherwise would have been in the same spot. Sorry and thank you @Pike

**Pull request merged**
