### PR TITLE
Remove duplicate localization file inclusion in project, add latest es and fr strings

### PR DESCRIPTION
**Pull request by joeyg**
Due to a bug in the import locales script there are dupe references. This PR removes those

### CODE REVIEW

**Comment by devinreams** [comment]
Thanks @joeyg I'm going to merge this then run the import script again and see how that goes. 🤘

**Comment by joeyg** [comment]
> Thanks @joeyg I'm going to merge this then run the import script again and see how that goes. 🤘

I suspect some files are still being duplicated so double check before committing. And please let me know which files are being duped so I can fix that up.

**Comment by devinreams** [comment]
@joeyg thanks I re-ran the import on this branch and ended up removing dupes again (see commits if you haven't already).

I promise I have the latest import script (842aeed84919ff55ceb80d9784c95497b513d89d) so perhaps has to do with the fact we have them in CredentialProvider, lockbox-ios, and Shared?

**Comment by joeyg** [comment]
> @joeyg thanks I re-ran the import on this branch and ended up removing dupes again (see commits if you haven't already).
> 
> I promise I have the latest import script (842aeed84919ff55ceb80d9784c95497b513d89d) so perhaps has to do with the fact we have them in CredentialProvider, lockbox-ios, and Shared?

I just pushed up my changes to the import from this weekend (b6edd96b595f68eb5c1b15200b0d80b83ceb2569). Do you mind re-running when you have a chance?

**Comment by devinreams** [comment]
>I just pushed up my changes to the import from this weekend 

Cool, I just ran again. Can't tell but I may have missed the Common/Strings files so just manually removed and re-added the first time around (may not be your script).

Beyond that, nothing obvious seems to be causing dupes. Looking at the diff, just seems Xcode and your script like to fight over a) wrapping paths in double quotes and b) including more context in the inclusion comments and c) do different ordering. But overall the script ran and a clean/build went OK. 👌 

Thank you, @joeyg! 🙏

**Pull request merged**
