### PR TITLE
Fixed Issue #1151: Disabled ability to edit web address

### LINKED ISSUE #1151: Disable Editing of hostname
Edit credential work was just merged and is now behind a feature flag.  Currently you can edit a hostname. Disable the user's ability to edit this.

### PR DESCRIPTION
**Pull request by KrisJackson**
Fixes #1151 

Disabled ability to edit web address.  

## Testing and Review Notes

Open app. Log in. Click any login cell. Tap 'Edit'. User should be able to edit 'Username' and 'Password', but 'Web Address' textfield should not be editable.

## Screenshot (Before)

Simulator Screen Shot - iPhone 11 - 2020-05-22 at 15 14 14

## Screenshot (After)

Simulator Screen Shot - iPhone 11 - 2020-05-22 at 15 15 02

## To Do

- add “WIP” to the PR title if pushing up but not complete nor ready for review
- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - optional: consider adding integration tests (UI specs)
- consider running this branch in the simulator and check for warnings
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)

### CODE REVIEW

**Comment by kaylagalway** [comment]
Great work on this @KrisJackson ! Would it be possible for us to make it a little clearer to the user that it is no longer possible to interact with this field specificially when editing? Normally you can click the url to visit it - and now the cell still responds with the "didSelect" default color change animation behavior when clicked. I wonder if we should gray out the URL to try to make it clearer it can not be edited or clicked? And possibly turn off the cell click animation?

**Comment by KrisJackson** [comment]
> Great work on this @KrisJackson ! Would it be possible for us to make it a little clearer to the user that it is no longer possible to interact with this field specificially when editing? Normally you can click the url to visit it - and now the cell still responds with the "didSelect" default color change animation behavior when clicked. I wonder if we should gray out the URL to try to make it clearer it can not be edited or clicked? And possibly turn off the cell click animation?

@kaylagalway Yes. I can definitely get that done for you. I agree. The way that I have it now is a little confusing. I'll get back to you shortly.

**Comment by KrisJackson** [comment]
> Great work on this @KrisJackson ! Would it be possible for us to make it a little clearer to the user that it is no longer possible to interact with this field specificially when editing? Normally you can click the url to visit it - and now the cell still responds with the "didSelect" default color change animation behavior when clicked. I wonder if we should gray out the URL to try to make it clearer it can not be edited or clicked? And possibly turn off the cell click animation?

Branch has been updated. Let me know what you think when you have time.

**Comment by kaylagalway** [comment]
Looks good, thanks! Merging

**Pull request merged**
