### PR TITLE
Fixed Issues #1152, #1156, #1233, and #1172: Fixed issues related to Discard, Save, and Reveal password in Edit mode

### LINKED ISSUE #1152: Edit Credential: Error Messaging
There is not currently any error messaging when editing a credential. Verify error messaging for edit on android and duplicate this functionality.

### LINKED ISSUE #1156: Changes to password in edit view are not saved when hide/show password
## Steps to reproduce
Select a login entry
Select show password
Edit password by removing some chars
Save changes
Click to hide the modified password and show it again
### Expected behavior
Changes in password are done
### Actual behavior
Changes are not done. If you go to a different entry and then  go back to the edited one, the changes are done
### Device & build information
* Device: iPad Air (3rd gen)
* Build version: master 8a7bd63

### Notes
Attachments:  Please see [video attached](https://youtu.be/gXlocgvZl0w).

### PR DESCRIPTION
**Pull request by KrisJackson**
Fixes #1152 #1156 #1172 #1233

This PR fixes all of the following issue related to Discard, Save, and Reveal password in Edit mode. Without this PR, there are 4 major issues that I noticed (some were already reported):

1. Discard does not revert text back to the original string in the username and password fields. Before this PR, the user had to physically click out of the page and open it again to see the discarded changes.
2. When Save is clicked by the user, the Hide/Reveal password function does not update the password value to the updated string. The user has to exit and re-enter the page to see the changes to the password.
3. The password field saves the "•" values when a password is hidden and 'Save' has been clicked. 
4. There is no error handling for empty fields when saving a username or password. 

This PR fixes all the above issues that I noticed related to Edit mode. Below are screen shots of the error handling (with error handling, I also included haptic feedback).

## Screenshot

Simulator Screen Shot - iPhone 11 - 2020-05-23 at 22 29 45

## To Do

- add “WIP” to the PR title if pushing up but not complete nor ready for review
- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - optional: consider adding integration tests (UI specs)
- consider running this branch in the simulator and check for warnings
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)

### CODE REVIEW

**Comment by kaylagalway** [comment]
Hey @KrisJackson if you have time - could you resolve the merge conflicts on this PR?

**Comment by KrisJackson** [comment]
@kaylagalway Should be fixed now. Let me know if it works

**Comment by kaylagalway** [comment]
I'll be offline for two weeks on short term leave, but will be reviewing whatever pull requests I still haven't merged when I get back.  A good amount of them should be in the late June release we will be doing. Thanks for all your hard work!

**Comment by KrisJackson** [comment]
No worries at all. Thanks for reviewing my code and allowing me to contribute!

**Pull request closed without merging**
